# Generated by Django 4.0.4 on 2022-05-31 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clé',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commentaire', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commentaire', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pièce',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_salle', models.CharField(max_length=100)),
                ('commentaire', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ressource_Info',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('commentaire', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Rôle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('commentaire', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('commentaire', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prénom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=20)),
                ('commentaire', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Responsabilité',
            fields=[
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur')),
                ('resp_pièce', models.BooleanField()),
                ('resp_clé', models.BooleanField()),
                ('resp_machine', models.BooleanField()),
                ('resp_ressource_info', models.BooleanField()),
                ('commentaire', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur_Statut',
            fields=[
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur')),
                ('date_début', models.DateField()),
                ('date_fin', models.DateField()),
                ('commentaire', models.CharField(max_length=150)),
                ('id_statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeressources.statut')),
            ],
            options={
                'unique_together': {('id_utilisateur', 'id_statut')},
            },
        ),
        migrations.CreateModel(
            name='Utilisateur_Rôle',
            fields=[
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur')),
                ('date_début', models.DateField()),
                ('date_fin', models.DateField()),
                ('commentaire', models.CharField(max_length=150)),
                ('id_rôle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeressources.rôle')),
            ],
            options={
                'unique_together': {('id_utilisateur', 'id_rôle')},
            },
        ),
        migrations.CreateModel(
            name='Utilisateur_Ressource_Info',
            fields=[
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur')),
                ('date_début', models.DateField()),
                ('date_fin', models.DateField()),
                ('commentaire', models.CharField(max_length=150)),
                ('id_ressource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeressources.ressource_info')),
            ],
            options={
                'unique_together': {('id_utilisateur', 'id_ressource')},
            },
        ),
        migrations.CreateModel(
            name='Utilisateur_Pièce',
            fields=[
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur')),
                ('date_début', models.DateField()),
                ('date_fin', models.DateField()),
                ('commentaire', models.CharField(max_length=150)),
                ('id_pièce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeressources.pièce')),
            ],
            options={
                'unique_together': {('id_utilisateur', 'id_pièce')},
            },
        ),
        migrations.CreateModel(
            name='Utilisateur_Machine',
            fields=[
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur')),
                ('date_début', models.DateField()),
                ('date_fin', models.DateField()),
                ('commentaire', models.CharField(max_length=150)),
                ('id_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeressources.machine')),
            ],
            options={
                'unique_together': {('id_utilisateur', 'id_machine')},
            },
        ),
        migrations.CreateModel(
            name='Utilisateur_Clé',
            fields=[
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur')),
                ('date_début', models.DateField()),
                ('date_fin', models.DateField()),
                ('commentaire', models.CharField(max_length=150)),
                ('id_clef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeressources.clé')),
            ],
            options={
                'unique_together': {('id_utilisateur', 'id_clef')},
            },
        ),
        migrations.CreateModel(
            name='Pièce_Clé',
            fields=[
                ('id_pièce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.pièce')),
                ('commentaire', models.CharField(max_length=150)),
                ('id_clé', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeressources.clé')),
            ],
            options={
                'unique_together': {('id_pièce', 'id_clé')},
            },
        ),
    ]
