# Generated by Django 4.0.4 on 2022-06-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeressources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur_clé',
            name='responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur_machine',
            name='responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur_pièce',
            name='responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur_ressource_info',
            name='responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pièce_clé',
            name='id_pièce',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.pièce'),
        ),
        migrations.AlterField(
            model_name='utilisateur_clé',
            name='id_utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur_machine',
            name='id_utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur_pièce',
            name='id_utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur_ressource_info',
            name='id_utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur_rôle',
            name='id_utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur'),
        ),
        migrations.AlterField(
            model_name='utilisateur_statut',
            name='id_utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meeressources.utilisateur'),
        ),
        migrations.DeleteModel(
            name='Responsabilité',
        ),
    ]
