# Generated by Django 4.0.4 on 2022-06-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeressources', '0002_utilisateur_clé_responsable_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='utilisateur_rôle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='utilisateur_rôle',
            name='id_rôle',
        ),
        migrations.RemoveField(
            model_name='utilisateur_rôle',
            name='id_utilisateur',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='rôle',
            field=models.CharField(blank=True, choices=[('a', 'Administrateur'), ('u', 'Utilisateur_simple'), ('d', 'Administrateur_délégué')], default='u', max_length=1),
        ),
        migrations.DeleteModel(
            name='Rôle',
        ),
        migrations.DeleteModel(
            name='Utilisateur_Rôle',
        ),
    ]
